name: Reka Keep Alive

on:
  schedule:
    # Se ejecuta cada 12 minutos (Render duerme a los 15)
    - cron: '*/12 * * * *' 
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pesta√±a Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Despertando a Reka
        run: |
          curl -f https://reka-backend-m19z.onrender.com/
